coverage:
  status:
    project:
      default: off
      adder:
        flags: adder
      subtractor:
        target: 50%
        flags: subtractor
flags:
  adder:
    paths:
      - adder/
    assume: true
  subtractor:
    paths:
      - subtractor/
    assume: true
  tests:
    paths:
      - __tests__
